esphome:
  name: energymeter
  platform: ESP32
  board: esp32dev

logger:
  level: VERBOSE

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 1
  power_pin: GPIO5

status_led:
  pin: GPIO0

time:
  - platform: sntp
    id: my_time

api:

ota:

web_server:
  port: 80

uart:
  - id: mod_bus
    tx_pin: GPIO12
    rx_pin: GPIO13
    baud_rate: 9600
    stop_bits: 1
  - id: dsmr_bus
    baud_rate: 115200
    rx_pin: 
      number: GPIO15
      inverted: true
      mode:
        input: true

modbus:
  flow_control_pin: GPIO4
  id: modbus1
  uart_id: mod_bus

modbus_controller:
  - id: epever
    ## the Modbus device addr
    address: 247
    modbus_id: modbus1
    setup_priority: -10

sensor:
  - platform: modbus_controller
    modbus_controller_id: epever
    name: "Power"
    id: inverter_power
    state_class: measurement
    device_class: power
    icon: mdi:flash-outline
    register_type: holding
    address: 0x0233
    unit_of_measurement: "W"
    value_type: U_WORD
  - platform: modbus_controller
    modbus_controller_id: epever
    name: "Energy"
    id: inverter_energy
    state_class: total_increasing
    device_class: energy
    register_type: holding
    address: 0x0222
    unit_of_measurement: "kWh"
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: epever
    name: "Vac"
    id: inverter_vac
    register_type: holding
    address: 0x0304
    unit_of_measurement: "V"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: epever
    name: "Iac"
    id: inverter_iac
    register_type: holding
    address: 0x0307
    unit_of_measurement: "A"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: epever
    name: "Vpv"
    id: inverter_vpv
    register_type: holding
    address: 0x0300
    unit_of_measurement: "V"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: epever
    name: "Ipv"
    id: inverter_ipv
    register_type: holding
    address: 0x0302
    unit_of_measurement: "A"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1